name = input("What is your name?")
print(f"Hello {name}! I am going to tell you some jokes now! press enter to continue.")
input("")
print("What do you call a fake noodle?")
input ("")
print("An impasta!!!")
input("")
print("why do bees have sticky hair?")
input("")
print ("because they use honeycombs!!!")
input("")
print("Why don't eggs tell jokes?")
input("")
print ("They would crack each other up!!!")
